In [ ]:

! pip install pymongo ortools
from pymongo import MongoClient
import urllib.parse
from datetime import datetime, timedelta
import pandas as pd
import numpy as np
username = urllib.parse.quote_plus("admin")             # Логин админстратора
password = urllib.parse.quote_plus("9!qUq9dq")          # Пароль администратора


host = "falupodikop.beget.app"  # Адрес сервера / доменное имя

client = MongoClient(f"mongodb://{username}:{password}@{host}")
db = client['rote']
print(f"mongodb://{username}:{password}@{host}")

Collecting pymongo
  Downloading pymongo-4.18.2-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (10 kB)
Collecting ortools
  Downloading ortools-9.15.6755-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (3.3 kB)
Collecting dnspython<3.0.0,>=2.7.0 (from pymongo)
  Downloading dnspython-2.8.0-py3-none-any.whl.metadata (5.7 kB)
Collecting absl-py>=2.0.0 (from ortools)
  Downloading absl_py-2.5.0-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: numpy>=2.0.2 in /usr/local/lib/python3.13/dist-packages (from ortools) (2.1.3)
Requirement already satisfied: pandas>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from ortools) (2.2.3)
Collecting protobuf<6.34,>=6.33.1 (from ortools)
  Downloading protobuf-6.33.6-cp39-abi3-manylinux2014_x86_64.whl.metadata (593 bytes)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.13/dist-packages (from ortools) (4.16.0)
Requirement already satisfied: immutabledict>=3.0.0 in /usr/local/lib/python3.13/dist-packages (from ortools) (4.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas>=2.0.0->ortools) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas>=2.0.0->ortools) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas>=2.0.0->ortools) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas>=2.0.0->ortools) (1.17.0)
Downloading pymongo-4.18.2-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 15.7 MB/s eta 0:00:00
Downloading ortools-9.15.6755-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (29.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 29.8/29.8 MB 45.0 MB/s eta 0:00:00
Downloading absl_py-2.5.0-py3-none-any.whl (137 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.4/137.4 kB 10.4 MB/s eta 0:00:00
Downloading dnspython-2.8.0-py3-none-any.whl (331 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 331.1/331.1 kB 21.2 MB/s eta 0:00:00
Downloading protobuf-6.33.6-cp39-abi3-manylinux2014_x86_64.whl (323 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 323.4/323.4 kB 23.1 MB/s eta 0:00:00
Installing collected packages: protobuf, dnspython, absl-py, pymongo, ortools
  Attempting uninstall: protobuf
    Found existing installation: protobuf 5.29.6
    Uninstalling protobuf-5.29.6:
      Successfully uninstalled protobuf-5.29.6
  Attempting uninstall: absl-py
    Found existing installation: absl-py 1.4.0
    Uninstalling absl-py-1.4.0:
      Successfully uninstalled absl-py-1.4.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-ai-generativelanguage 0.6.15 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 6.33.6 which is incompatible.
grpcio-status 1.71.2 requires protobuf<6.0dev,>=5.26.1, but you have protobuf 6.33.6 which is incompatible.
Successfully installed absl-py-2.5.0 dnspython-2.8.0 ortools-9.15.6755 protobuf-6.33.6 pymongo-4.18.2

mongodb://admin:9%21qUq9dq@falupodikop.beget.app

In [ ]:
ENGINEERS = [
    {"shift": [0, 1440], "equip": ['Подключение','Дозаказ'], "speed": 5.0},
    {"shift": [0, 1440], "equip": ['Дозаказ','Локальная заявка'], "speed": 10.0},
    {"shift": [60, 1440], "equip": ['Подключение','Дозаказ','Локальная заявка','Глобальная проблема'], "speed": 15.0},
]

In [ ]:
df= pd.DataFrame(db.all.find())
df=df.loc[df.okrug=='Югоцентр']

mask = df['request_id'].str.contains('дрес', na=False)
df = df.loc[mask.sort_values(ascending=False).index].reset_index(drop=True)
df

,_id,request_id,request_type_bk,status_bk,request_type_hd,start_time,end_time,district,address,brigade,Подключение,gigabit_connection,train,okrug,lat,lon
0,6ab4347f41a8f67fe20e61c2,Адрес офиса,nan,NaN,nan,nan,nan,nan,"г.Москва проезд Симферопольский, д.7",NaN,NaN,True,True,Югоцентр,55.664757,37.615839
1,6ab4347f41a8f67fe20e618b,78540,Подключение,NaN,Конвергенция абонента,17.08.2026 18:00,17.08.2026 20:00,Даниловский,"Город Москва, ул.Восточная, д. 2 к 2",NaN,NaN,True,True,Югоцентр,55.727273,37.650564
2,6ab4347f41a8f67fe20e61a5,6957,Подключение,NaN,Конвергенция абонента,17.08.2026 10:00,17.08.2026 12:00,Хамовники,"Город Москва, ул.Усачёва, д. 25",NaN,NaN,True,True,Югоцентр,55.724951,37.565125
3,6ab4347f41a8f67fe20e61a4,79719,Подключение,NaN,Заказ подключения/Дозаказ оборудования,17.08.2026 12:00,17.08.2026 14:00,Хамовники,"Город Москва, б-р.Смоленский, д. 17 стр. 1",NaN,NaN,True,True,Югоцентр,55.742435,37.582029
4,6ab4347f41a8f67fe20e61a3,90373,Подключение,NaN,Конвергенция абонента,17.08.2026 12:00,17.08.2026 14:00,Нагатинский Затон,"Город Москва, ул.Коломенская, д. 5",NaN,NaN,True,True,Югоцентр,55.682173,37.704796
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,6ab4347e41a8f67fe20e6174,305892304,Локальная заявка,В работе,Нет линка,17.08.2026 18:00,17.08.2026 20:00,Нагорный,"Город Москва, б-р.Симферопольский, д. 27, кв. 6",Прокопенко Вячеслав,NaN,True,False,Югоцентр,55.648682,37.606221
109,6ab4347e41a8f67fe20e6173,305887469,Локальная заявка,Отправлена,Нет линка,17.08.2026 20:00,17.08.2026 22:00,Зюзино,"Город Москва, пр-кт.Балаклавский, д. 50, кв. 18",Переладов Алексей,NaN,True,False,Югоцентр,55.651630,37.588500
110,6ab4347e41a8f67fe20e6172,305887153,Локальная заявка,Отправлена,TVE/ENT. Другие ошибки,17.08.2026 18:00,17.08.2026 20:00,Академический,"Город Москва, ул.Винокурова, д. 5/6 к 2, кв. 41",Брюзгин Ярослав,NaN,True,False,Югоцентр,55.684364,37.598205
111,6ab4347e41a8f67fe20e6171,305897880,Локальная заявка,Отправлена,Нет линка,17.08.2026 20:00,17.08.2026 22:00,Нагатино - Садовники,"Город Москва, ул.Академика Миллионщикова, д. 1...",Рыбалкин Егор,NaN,True,False,Югоцентр,55.670021,37.649800
112,6ab4347f41a8f67fe20e618a,32840,Подключение,NaN,Конвергенция абонента,17.08.2026 18:00,17.08.2026 20:00,Даниловский,"Город Москва, проезд.3-й Павелецкий, д. 9",NaN,NaN,True,True,Югоцентр,55.487238,37.468672

In [ ]:
import requests
import itertools
def get_loc_matrix( location):
        res_dis_all = location[['lon', 'lat']].astype(str).apply(lambda x: ','.join(x), axis=1)
        res_dis = list(res_dis_all.unique())
        fin = np.arange(len(res_dis))
        d_matrix = pd.DataFrame(columns=res_dis, index=res_dis)
        res_dis_str = ';'.join(res_dis)
        url = 'http://router.project-osrm.org/table/v1/driving/' + res_dis_str + '?annotations=distance'
        lrin = []
        for i in range(fin.max() // 100 + 1):
            lrin += [list(fin[i * 100:i * 100 + 100])]
        lrin = list(itertools.product(lrin, lrin))
        for k, i in enumerate(lrin):
            r = requests.post(url + '&sources=' + ';'.join([str(ii) for ii in i[0]]) + '&destinations=' + ';'.join([str(ii) for ii in i[1]]))
            print(r, int(k * 100 / len(lrin)))
            ind = [res_dis[ii] for ii in i[0]]
            col = [res_dis[ii] for ii in i[1]]
            d_matrix.loc[ind, col] = r.json()['distances']
        def foo_bar(x):
            if x is None or x < 0:
                x = 0
            return x
        d_matrix = d_matrix.map(foo_bar)
        d_matrix = d_matrix.loc[res_dis_all, res_dis_all]
        return d_matrix
d_matrix= get_loc_matrix(df)
d_matrix

<Response [200]> 0

,"37.615839,55.664757","37.650564,55.727273","37.565125,55.724951","37.582029,55.742435","37.704796,55.682173","37.673228,55.682738","37.583081,55.657307","37.597872,55.64484","37.581939,55.694173","37.67939,55.68353",...,"39.811677,54.619409","37.68727,55.687937","37.694305,55.677753","37.66141,55.701103","37.609656,55.656142","37.606221,55.648682","37.5885,55.65163","37.598205,55.684364","37.6498,55.670021","37.468672,55.487238"
"37.615839,55.664757",0.0,11685.3,12201.5,15023.3,7960.0,5657.4,3194.5,3108.4,6172.4,5801.8,...,219400.2,6809.1,7073.5,7875.6,1474.9,2990.8,2623.5,4029.7,3039.5,26831.1
"37.650564,55.727273",9389.4,0.0,9903.6,8735.1,10652.1,8349.5,11225.0,12347.7,8372.8,8493.8,...,200087.7,8666.5,9765.5,4615.0,10586.7,12352.9,12150.2,7228.6,9110.8,35345.3
"37.565125,55.724951",11718.2,7387.8,0.0,3522.7,16060.5,13757.9,12350.2,13794.1,6608.4,13902.3,...,208318.2,14074.9,15174.0,9749.0,12915.5,14681.7,13045.7,8353.8,13292.4,37674.1
"37.582029,55.742435",11086.2,5659.5,3219.4,0.0,15978.6,13676.0,12921.9,14044.5,8366.1,13820.4,...,205414.2,13993.0,15092.1,10400.6,12283.5,14049.8,13847.0,8925.4,12660.4,37042.1
"37.704796,55.682173",8431.8,10333.3,16574.2,18013.6,0.0,2953.4,10716.3,10630.2,15384.4,2419.2,...,205259.6,3273.8,967.4,6697.0,8996.7,10512.6,10145.2,11551.5,5806.1,34535.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"37.606221,55.648682",3313.9,12574.3,13949.3,15305.4,9635.0,7332.4,2863.3,1528.9,7920.2,7476.8,...,218204.2,8484.1,8748.5,9550.6,1306.6,0.0,1789.2,5777.6,4714.6,25635.0
"37.5885,55.65163",4768.5,12610.8,13048.9,15870.8,11089.6,8787.0,1074.0,2732.7,7012.5,8931.3,...,220671.6,9938.6,10203.0,10709.4,2761.1,3508.1,0.0,4877.2,6169.1,28102.4
"37.598205,55.684364",3782.8,7977.9,8416.0,11237.9,12388.0,10085.5,4216.0,5659.9,1953.8,10229.8,...,204645.8,10402.4,11501.5,6076.5,4882.7,6666.3,4911.5,0.0,6724.1,30506.5
"37.6498,55.670021",4003.8,9686.6,12991.7,14115.0,6134.8,3832.2,5701.1,5615.0,8679.0,3976.5,...,204612.9,4983.8,5248.2,6050.4,3981.5,5497.4,5130.0,6536.3,0.0,29170.4
"37.468672,55.487238",30113.4,37425.6,39033.3,40156.7,34285.2,31982.6,29268.2,27429.5,34127.8,32126.9,...,213867.0,33134.3,33398.6,34200.8,27849.5,26755.9,28332.2,31985.1,29807.9,0.0

In [ ]:
Equip_dick={'Подключение': 90,
'Дозаказ': 40,
'Локальная заявка':50,
'Глобальная проблема':100 }

prior={'Подключение': 1,
'Дозаказ': 0,
'Локальная заявка':0,
'Глобальная проблема':3 }


df['duration']=df.request_type_bk.map(Equip_dick)
df["req_equip"]= df.request_type_bk
df['priority']
def fill(x):
   x= list(x)
   if x[0]=='nan':
      return [0,1440]
   times=[]
   for i in list(x):

     Tst= i.split(' ')[1]
     t=int(Tst.split(':')[0])*60+int(Tst.split(':')[1])
     times +=[int(t)]
   return times

df['tw'] = df[[ 'start_time', 'end_time']] .apply ( lambda x: fill(x), axis=1)

features=['tw', 'duration', 'req_equip','priority']
JOBS= df[features].to_dict('records')
JOBS

KeyError: "['priority'] not in index"

In [ ]:

import math
from ortools.constraint_solver import routing_enums_pb2
from ortools.constraint_solver import pywrapcp

# ==========================================
# 1. ВХОДНЫЕ ДАННЫЕ (ВАШИ СПРАВОЧНИКИ)
# ==========================================


# Справочник оборудования
EQUIPMENT = ['Подключение','Дозаказ','Локальная заявка','Глобальная проблема']
# Заявки: (индекс локации, временное окно [мин], длительность работ [мин], требуемое оборудование)

BASE_TIME_MATRIX = d_matrix.values.tolist()

# ==========================================
# 3. НАСТРОЙКА МОДЕЛИ OR-TOOLS
# ==========================================
def main():
    num_locations = len(JOBS)
    num_vehicles = len(ENGINEERS)
    depot = 0

    # Менеджер индексов
    manager = pywrapcp.RoutingIndexManager(num_locations, num_vehicles, depot)
    routing = pywrapcp.RoutingModel(manager)

    # --- Ограничение 1: Совместимость "Работа -> Оборудование" ---
    # Запрещаем инженеру посещать заявку, если у него нет нужного оборудования
    for job_idx, job in enumerate(JOBS):
        if job_idx==0 : continue
        node_idx = job_idx  # 0 - это депо, заявки начинаются с 1
        allowed_vehicles = []
        for v_idx, eng in enumerate(ENGINEERS):
            # Проверяем, есть ли у инженера ВСЕ требуемые для заявки инструменты
            if any([eq == job["req_equip"] for eq in eng["equip"]]):
                allowed_vehicles.append(v_idx)
        node_idx_routing = manager.NodeToIndex(node_idx)
        allowed_vehicles = [int(v) for v in allowed_vehicles]  # явный int
        if allowed_vehicles:  # защита от пустого списка
          vehicle_var = routing.VehicleVar(node_idx_routing)
          vehicle_var.SetValues([-1] + allowed_vehicles)  #
          routing.AddDisjunction([node_idx_routing], 10**12)


        else:
         routing.AddDisjunction([node_idx_routing], 0)

    # --- Коллбэк времени (Дорога + Длительность работ) ---
    def create_time_callback(vehicle_id):

      def callback(from_index, to_index):

        from_index = int(from_index)
        to_index = int(to_index)

        from_node = manager.IndexToNode(from_index)
        to_node = manager.IndexToNode(to_index)

        speed = ENGINEERS[vehicle_id]["speed"]

        travel_time = int(
            BASE_TIME_MATRIX[from_node][to_node] * 60
            / (1000 * speed)
        )

        service_time = 0

        if from_node != 0:
            service_time = int(JOBS[from_node]["duration"])

        return int(travel_time + service_time)

      return callback

    transit_callbacks = []
    for v in range(num_vehicles):
      callback = create_time_callback(v)

      transit_idx = routing.RegisterTransitCallback(callback)

      transit_callbacks.append(transit_idx)

      routing.SetArcCostEvaluatorOfVehicle(
        transit_idx,
        v
    )

    # --- Ограничение 2: Временные окна и График инженеров ---
    time = "Time"
    # Максимальное время (с запасом), параметр: имя, макс время, учет времени в депо
    routing.AddDimensionWithVehicleTransitAndCapacity(
        transit_callbacks,
        1440, # Максимальное ожидание (slack)
        [1440]*num_vehicles, # Максимальное время на машину (глобальный лимит)
        False, # Не форсировать начало с нуля (мы зададим это вручную)
        time,
    )
    time_dimension = routing.GetDimensionOrDie(time)

    # Применяем временные окна заявок
    for job_idx, job in enumerate(JOBS):
        if job_idx==0 : continue
        index = manager.NodeToIndex(job_idx)
        # CumulVar - это время прибытия/начала в узле
        time_dimension.CumulVar(index).SetRange(job["tw"][0], job["tw"][1])


    '''
        time_dimension.SetCumulVarSoftUpperBound(
         index,
         job["tw"][0],
         job["priority"] * 1000
         )
    '''
    # Применяем графики работы инженеров (смены)
    for v_idx, eng in enumerate(ENGINEERS):
        start_index = routing.Start(v_idx)
        end_index = routing.End(v_idx)

        # Инженер выезжает ровно в начале своей смены
        time_dimension.CumulVar(start_index).SetRange(eng["shift"][0], eng["shift"][0])
        # Инженер должен вернуться до конца смены
        time_dimension.CumulVar(end_index).SetRange(0, eng["shift"][1])

    # ==========================================
    # 4. ПАРАМЕТРЫ ПОИСКА И РЕШЕНИЕ
    # ==========================================
    search_parameters = pywrapcp.DefaultRoutingSearchParameters()
    search_parameters.first_solution_strategy = routing_enums_pb2.FirstSolutionStrategy.PATH_CHEAPEST_ARC
    search_parameters.local_search_metaheuristic = routing_enums_pb2.LocalSearchMetaheuristic.GUIDED_LOCAL_SEARCH
    search_parameters.time_limit.FromSeconds(5)

    # Решение
    solution = routing.SolveWithParameters(search_parameters)

    # ==========================================
    # 5. ВЫВОД РЕЗУЛЬТАТА
    # ==========================================
    if solution:
        print("=== МАРШРУТЫ ИНЖЕНЕРОВ ===")
        total_time = 0
        plan_output1=[]
        for vehicle_id in range(num_vehicles):
            index = routing.Start(vehicle_id)
            route_str = f"Инженер {vehicle_id + 1} (Смена: {ENGINEERS[vehicle_id]['shift']}, Инстр: {ENGINEERS[vehicle_id]['equip']}):\n"
            route_time = 0
            plan_output = ""

            while not routing.IsEnd(index):
                node_index = manager.IndexToNode(index)
                time_var = time_dimension.CumulVar(index)
                arr_time = solution.Min(time_var)

                if node_index == 0:
                    plan_output += f"  [Депо] Выезд в {arr_time} мин.\n"
                else:
                    job = JOBS[node_index]
                    plan_output += f"  -> Заявка {node_index} (Оборудование: {job['req_equip']})\n"
                    plan_output += f"     Прибытие: {arr_time} мин. | Окно: {job['tw']} | Длительность: {job['duration']} мин.\n"


                plan_output1 +=[[vehicle_id ,node_index, arr_time ]]
                index = solution.Value(routing.NextVar(index))

            # Финальная точка (возврат в депо)
            arr_time = solution.Min(time_dimension.CumulVar(routing.End(vehicle_id)))
            plan_output += f"  [Депо] Возврат в {arr_time} мин.\n"
            plan_output1 +=[[vehicle_id ,0, arr_time ]]
            route_time = arr_time - ENGINEERS[vehicle_id]["shift"][0]
            total_time += route_time

            # Печатаем только если инженер был задействован
            if route_time>0:print(route_str + plan_output + f"  Итого в пути/работе: {route_time} мин.\n")

        print(f"Общее время работы всех инженеров: {total_time} мин.")
    else:
        print("Решение не найдено!")
    return plan_output1

plan_output1= main()

=== МАРШРУТЫ ИНЖЕНЕРОВ ===
Инженер 1 (Смена: [0, 1440], Инстр: ['Подключение', 'Дозаказ']):
  [Депо] Выезд в 0 мин.
  -> Заявка 84 (Оборудование: Подключение)
     Прибытие: 600 мин. | Окно: [600, 720] | Длительность: 90.0 мин.
  -> Заявка 2 (Оборудование: Подключение)
     Прибытие: 690 мин. | Окно: [600, 720] | Длительность: 90.0 мин.
  -> Заявка 22 (Оборудование: Подключение)
     Прибытие: 865 мин. | Окно: [840, 960] | Длительность: 90.0 мин.
  -> Заявка 76 (Оборудование: Подключение)
     Прибытие: 968 мин. | Окно: [960, 1080] | Длительность: 90.0 мин.
  -> Заявка 20 (Оборудование: Подключение)
     Прибытие: 1058 мин. | Окно: [960, 1080] | Длительность: 90.0 мин.
  -> Заявка 86 (Оборудование: Дозаказ)
     Прибытие: 1200 мин. | Окно: [1200, 1320] | Длительность: 40.0 мин.
  -> Заявка 28 (Оборудование: Дозаказ)
     Прибытие: 1240 мин. | Окно: [1200, 1320] | Длительность: 40.0 мин.
  -> Заявка 25 (Оборудование: Подключение)
     Прибытие: 1314 мин. | Окно: [1200, 1320] | Длительность: 90.0 мин.
  [Депо] Возврат в 1424 мин.
  Итого в пути/работе: 1424 мин.

Инженер 2 (Смена: [0, 1440], Инстр: ['Дозаказ', 'Локальная заявка']):
  [Депо] Выезд в 0 мин.
  -> Заявка 107 (Оборудование: Локальная заявка)
     Прибытие: 600 мин. | Окно: [600, 720] | Длительность: 50.0 мин.
  -> Заявка 51 (Оборудование: Локальная заявка)
     Прибытие: 650 мин. | Окно: [600, 720] | Длительность: 50.0 мин.
  -> Заявка 34 (Оборудование: Локальная заявка)
     Прибытие: 718 мин. | Окно: [600, 720] | Длительность: 50.0 мин.
  -> Заявка 32 (Оборудование: Локальная заявка)
     Прибытие: 840 мин. | Окно: [840, 960] | Длительность: 50.0 мин.
  -> Заявка 88 (Оборудование: Локальная заявка)
     Прибытие: 890 мин. | Окно: [840, 960] | Длительность: 50.0 мин.
  -> Заявка 38 (Оборудование: Локальная заявка)
     Прибытие: 972 мин. | Окно: [960, 1080] | Длительность: 50.0 мин.
  -> Заявка 94 (Оборудование: Локальная заявка)
     Прибытие: 1022 мин. | Окно: [960, 1080] | Длительность: 50.0 мин.
  -> Заявка 92 (Оборудование: Локальная заявка)
     Прибытие: 1109 мин. | Окно: [1080, 1200] | Длительность: 50.0 мин.
  -> Заявка 36 (Оборудование: Локальная заявка)
     Прибытие: 1159 мин. | Окно: [1080, 1200] | Длительность: 50.0 мин.
  -> Заявка 111 (Оборудование: Локальная заявка)
     Прибытие: 1235 мин. | Окно: [1200, 1320] | Длительность: 50.0 мин.
  -> Заявка 43 (Оборудование: Локальная заявка)
     Прибытие: 1297 мин. | Окно: [1200, 1320] | Длительность: 50.0 мин.
  [Депо] Возврат в 1363 мин.
  Итого в пути/работе: 1363 мин.

Инженер 3 (Смена: [60, 1440], Инстр: ['Подключение', 'Дозаказ', 'Локальная заявка', 'Глобальная проблема']):
  [Депо] Выезд в 60 мин.
  -> Заявка 90 (Оборудование: Локальная заявка)
     Прибытие: 600 мин. | Окно: [600, 720] | Длительность: 50.0 мин.
  -> Заявка 30 (Оборудование: Локальная заявка)
     Прибытие: 676 мин. | Окно: [600, 720] | Длительность: 50.0 мин.
  -> Заявка 87 (Оборудование: Локальная заявка)
     Прибытие: 737 мин. | Окно: [720, 840] | Длительность: 50.0 мин.
  -> Заявка 42 (Оборудование: Локальная заявка)
     Прибытие: 787 мин. | Окно: [720, 840] | Длительность: 50.0 мин.
  -> Заявка 35 (Оборудование: Локальная заявка)
     Прибытие: 854 мин. | Окно: [840, 960] | Длительность: 50.0 мин.
  -> Заявка 91 (Оборудование: Локальная заявка)
     Прибытие: 904 мин. | Окно: [840, 960] | Длительность: 50.0 мин.
  -> Заявка 97 (Оборудование: Локальная заявка)
     Прибытие: 968 мин. | Окно: [960, 1080] | Длительность: 50.0 мин.
  -> Заявка 110 (Оборудование: Локальная заявка)
     Прибытие: 1080 мин. | Окно: [1080, 1200] | Длительность: 50.0 мин.
  -> Заявка 54 (Оборудование: Локальная заявка)
     Прибытие: 1142 мин. | Окно: [1080, 1200] | Длительность: 50.0 мин.
  -> Заявка 52 (Оборудование: Локальная заявка)
     Прибытие: 1193 мин. | Окно: [1080, 1200] | Длительность: 50.0 мин.
  -> Заявка 46 (Оборудование: Локальная заявка)
     Прибытие: 1269 мин. | Окно: [1200, 1320] | Длительность: 50.0 мин.
  -> Заявка 102 (Оборудование: Локальная заявка)
     Прибытие: 1319 мин. | Окно: [1200, 1320] | Длительность: 50.0 мин.
  [Депо] Возврат в 1397 мин.
  Итого в пути/работе: 1337 мин.

Общее время работы всех инженеров: 4124 мин.

[[0, 0, 0],
 [0, 84, 600],
 [0, 2, 690],
 [0, 22, 865],
 [0, 76, 968],
 [0, 20, 1058],
 [0, 86, 1200],
 [0, 28, 1240],
 [0, 25, 1314],
 [0, 0, 1424],
 [1, 0, 0],
 [1, 107, 600],
 [1, 51, 650],
 [1, 34, 718],
 [1, 32, 840],
 [1, 88, 890],
 [1, 38, 972],
 [1, 94, 1022],
 [1, 92, 1109],
 [1, 36, 1159],
 [1, 111, 1235],
 [1, 43, 1297],
 [1, 0, 1363],
 [2, 0, 60],
 [2, 90, 600],
 [2, 30, 676],
 [2, 87, 737],
 [2, 42, 787],
 [2, 35, 854],
 [2, 91, 904],
 [2, 97, 968],
 [2, 110, 1080],
 [2, 54, 1142],
 [2, 52, 1193],
 [2, 46, 1269],
 [2, 102, 1319],
 [2, 0, 1397]]

In [ ]:

df[]=df.index

pd.DataFrame(plan_output1).merge(df, on=1, how='left')

/tmp/ipykernel_731/2087418387.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[1]=df.index

    0    1     2            tw  duration         req_equip
0   0    0     0     [0, 1440]       NaN               nan
1   0   84   600    [600, 720]      90.0       Подключение
2   0    2   690    [600, 720]      90.0       Подключение
3   0   22   865    [840, 960]      90.0       Подключение
4   0   76   968   [960, 1080]      90.0       Подключение
5   0   20  1058   [960, 1080]      90.0       Подключение
6   0   86  1200  [1200, 1320]      40.0           Дозаказ
7   0   28  1240  [1200, 1320]      40.0           Дозаказ
8   0   25  1314  [1200, 1320]      90.0       Подключение
9   0    0  1424     [0, 1440]       NaN               nan
10  1    0     0     [0, 1440]       NaN               nan
11  1  107   600    [600, 720]      50.0  Локальная заявка
12  1   51   650    [600, 720]      50.0  Локальная заявка
13  1   34   718    [600, 720]      50.0  Локальная заявка
14  1   32   840    [840, 960]      50.0  Локальная заявка
15  1   88   890    [840, 960]      50.0  Локальная заявка
16  1   38   972   [960, 1080]      50.0  Локальная заявка
17  1   94  1022   [960, 1080]      50.0  Локальная заявка
18  1   92  1109  [1080, 1200]      50.0  Локальная заявка
19  1   36  1159  [1080, 1200]      50.0  Локальная заявка
20  1  111  1235  [1200, 1320]      50.0  Локальная заявка
21  1   43  1297  [1200, 1320]      50.0  Локальная заявка
22  1    0  1363     [0, 1440]       NaN               nan
23  2    0    60     [0, 1440]       NaN               nan
24  2   90   600    [600, 720]      50.0  Локальная заявка
25  2   30   676    [600, 720]      50.0  Локальная заявка
26  2   87   737    [720, 840]      50.0  Локальная заявка
27  2   42   787    [720, 840]      50.0  Локальная заявка
28  2   35   854    [840, 960]      50.0  Локальная заявка
29  2   91   904    [840, 960]      50.0  Локальная заявка
30  2   97   968   [960, 1080]      50.0  Локальная заявка
31  2  110  1080  [1080, 1200]      50.0  Локальная заявка
32  2   54  1142  [1080, 1200]      50.0  Локальная заявка
33  2   52  1193  [1080, 1200]      50.0  Локальная заявка
34  2   46  1269  [1200, 1320]      50.0  Локальная заявка
35  2  102  1319  [1200, 1320]      50.0  Локальная заявка
36  2    0  1397     [0, 1440]       NaN               nan